// @ts-check
// ESLint for the backend side of the repo: services, @curo/shared, @curo/testing and database tooling.
// The portals in apps/ and @curo/web (packages/web) use the Next.js config instead.
import eslint from '@eslint/js';
import eslintPluginPrettierRecommended from 'eslint-plugin-prettier/recommended';
import globals from 'globals';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    ignores: [
      'apps/**',
      'packages/web/**',
      '**/dist/**',
      '**/coverage/**',
      // Generated by `npm run db:generate`; reviewed as SQL, not restyled.
      'database/migrations/**',
      '**/*.mjs',
      '**/*.js',
    ],
  },
  eslint.configs.recommended,
  ...tseslint.configs.recommendedTypeChecked,
  eslintPluginPrettierRecommended,
  {
    languageOptions: {
      globals: {
        ...globals.node,
        ...globals.jest,
      },
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
  },
  {
    rules: {
      // `const { secret, ...rest } = obj` is how fields get dropped.
      '@typescript-eslint/no-unused-vars': ['error', { ignoreRestSiblings: true }],
      'prettier/prettier': ['error', { endOfLine: 'auto' }],
    },
  },
);
