// @ts-check
// ESLint for the backend side of the repo: services, @curo/shared and database tooling.
// Each portal in apps/ keeps its own Next.js config.
import eslint from '@eslint/js';
import eslintPluginPrettierRecommended from 'eslint-plugin-prettier/recommended';
import globals from 'globals';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    ignores: [
      'apps/**',
      '**/dist/**',
      '**/coverage/**',
      // Generated by `npm run db:generate`; reviewed as SQL, not restyled.
      'database/migrations/**',
      '**/*.mjs',
      '**/*.js',
    ],
  },
  eslint.configs.recommended,
  ...tseslint.configs.recommendedTypeChecked,
  eslintPluginPrettierRecommended,
  {
    languageOptions: {
      globals: {
        ...globals.node,
        ...globals.jest,
      },
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
  },
  {
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-floating-promises': 'warn',
      // `const { secret, ...rest } = obj` is how fields get dropped.
      '@typescript-eslint/no-unused-vars': ['error', { ignoreRestSiblings: true }],
      // `any` flowing out of query results and request bodies. Warnings for now;
      // switch back to errors service by service as each one is typed properly.
      '@typescript-eslint/no-unsafe-argument': 'warn',
      '@typescript-eslint/no-unsafe-assignment': 'warn',
      '@typescript-eslint/no-unsafe-call': 'warn',
      '@typescript-eslint/no-unsafe-member-access': 'warn',
      '@typescript-eslint/no-unsafe-return': 'warn',
      'prettier/prettier': ['error', { endOfLine: 'auto' }],
    },
  },
);
