import { OmitType } from '@nestjs/swagger';
import { Type } from 'class-transformer';
import {
  IsArray,
  IsBoolean,
  IsNotEmpty,
  IsOptional,
  IsString,
  IsUUID,
  ValidateNested,
} from 'class-validator';
import { CreateEncounterDto } from './create-encounter.dto';
import { CreateLabOrderDto } from './create-lab-order.dto';
import { CreateNoteDto } from './create-note.dto';
import { CreatePrescriptionDto } from './create-prescription.dto';
import { CreateVitalsDto } from './create-vitals.dto';

// The records of a visit, without the patient and encounter they belong to:
// the visit supplies both.

export class VisitNoteDto extends OmitType(CreateNoteDto, [
  'patientId',
  'encounterId',
]) {}

export class VisitVitalDto extends OmitType(CreateVitalsDto, [
  'patientId',
  'encounterId',
  'appointmentId',
]) {}

export class VisitPrescriptionDto extends OmitType(CreatePrescriptionDto, [
  'patientId',
  'encounterId',
]) {}

export class VisitLabOrderDto extends OmitType(CreateLabOrderDto, [
  'patientId',
  'encounterId',
]) {}

export class VisitDiagnosisDto {
  @IsNotEmpty()
  @IsString()
  code: string; // ICD-10

  @IsNotEmpty()
  @IsString()
  display: string;

  @IsOptional()
  @IsBoolean()
  isPrimary?: boolean;
}

/** A signed visit: the encounter and every record made during it. */
export class CompleteVisitDto extends OmitType(CreateEncounterDto, [
  'periodEnd',
]) {
  // Generated by the client and kept with its draft, so signing again after a
  // lost response returns this visit instead of recording a second one.
  @IsUUID()
  id: string;

  @IsOptional()
  @ValidateNested()
  @Type(() => VisitNoteDto)
  note?: VisitNoteDto;

  // An omitted list defaults to empty; an explicit null is rejected.
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => VisitVitalDto)
  vitals: VisitVitalDto[] = [];

  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => VisitDiagnosisDto)
  diagnoses: VisitDiagnosisDto[] = [];

  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => VisitPrescriptionDto)
  prescriptions: VisitPrescriptionDto[] = [];

  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => VisitLabOrderDto)
  labOrders: VisitLabOrderDto[] = [];
}
