import {
  ConflictException,
  Injectable,
  NotFoundException,
} from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { DataSource, FindOptionsWhere, Repository } from 'typeorm';
import {
  ServiceRequest,
  Observation,
  Patient,
  QrCode,
} from '@curo/shared/database';
import {
  ServiceRequestStatus,
  ObservationStatus,
  NotificationEventType,
} from '@curo/shared/enums';
import { actorId, type AuthUser } from '@curo/shared/auth';
import { notifyPractitioner } from '@curo/shared/notifications';
import {
  parsePagination,
  toSearchset,
  PaginationQuery,
} from '@curo/shared/fhir';
import { DiagnosticReport } from '../entities/diagnostic-report.entity';
import { LabInstrument } from '../entities/lab-instrument.entity';
import { LabTestCatalog } from '../entities/lab-test-catalog.entity';
import { QCLog, QCStatus } from '../entities/qc-log.entity';
import { EnterResultsDto } from './dto/enter-results.dto';
import { ScanQrDto } from './dto/scan-qr.dto';
import { CreateInstrumentDto } from './dto/create-instrument.dto';
import { DiagnosticReportStatus, InstrumentStatus } from '../enums';
import { generateLabReportPdf } from './pdf.generator';
import { parseLabQr } from './lab-qr';

interface LabStaffRow {
  id: string;
  firstName: string;
  lastName: string;
  email: string;
  specialization: string | null;
  qualification: string | null;
  active: boolean;
}

function toFhirServiceRequest(s: ServiceRequest) {
  return {
    resourceType: 'ServiceRequest',
    id: s.id,
    status: s.status,
    code: { coding: [{ code: s.code, display: s.display }] },
    subject: { reference: `Patient/${s.patientId}` },
    requester: { reference: `Practitioner/${s.requesterId}` },
    authoredOn: s.authoredOn,
    priority: s.priority,
    testPanel: s.testPanel,
    receivedAt: s.receivedAt,
    completedAt: s.completedAt,
  };
}

function toFhirReport(r: DiagnosticReport) {
  return {
    resourceType: 'DiagnosticReport',
    id: r.id,
    status: r.status,
    code: { coding: [{ code: r.code, display: r.display }] },
    subject: { reference: `Patient/${r.patientId}` },
    performer: [{ reference: `Practitioner/${r.performerId}` }],
    basedOn: [{ reference: `ServiceRequest/${r.serviceRequestId}` }],
    effectiveDateTime: r.effectiveDateTime,
    issued: r.issued,
    conclusion: r.conclusion,
    result: (r.results ?? []).map((res) => ({ display: res.display })),
    presentedForm: r.pdfBase64
      ? [{ contentType: 'application/pdf', data: r.pdfBase64 }]
      : [],
  };
}

@Injectable()
export class LabService {
  constructor(
    @InjectRepository(ServiceRequest)
    private ordersRepo: Repository<ServiceRequest>,
    @InjectRepository(DiagnosticReport)
    private reportsRepo: Repository<DiagnosticReport>,
    @InjectRepository(QrCode)
    private qrRepo: Repository<QrCode>,
    @InjectRepository(Patient)
    private patientsRepo: Repository<Patient>,
    @InjectRepository(LabInstrument)
    private instrumentsRepo: Repository<LabInstrument>,
    @InjectRepository(LabTestCatalog)
    private catalogRepo: Repository<LabTestCatalog>,
    @InjectRepository(QCLog)
    private qcLogRepo: Repository<QCLog>,
    private dataSource: DataSource,
  ) {}

  // Tests a given lab offers (doctors browse before ordering).
  async getCatalog(organizationId?: string): Promise<LabTestCatalog[]> {
    const where: FindOptionsWhere<LabTestCatalog> = {
      active: true,
      ...(organizationId && { organizationId }),
    };
    return this.catalogRepo.find({ where, order: { name: 'ASC' } });
  }

  // Lab orders queue → FHIR searchset Bundle (paginated, optional status filter).
  async getOrders(status?: string, pagination: PaginationQuery = {}) {
    const { page, pageSize, skip, take } = parsePagination(pagination);
    const query = this.ordersRepo.createQueryBuilder('s');
    if (status) query.where('s.status = :status', { status });
    const [orders, total] = await query
      .orderBy('s.authoredOn', 'ASC')
      .skip(skip)
      .take(take)
      .getManyAndCount();
    return toSearchset(orders.map(toFhirServiceRequest), total, {
      page,
      pageSize,
      baseUrl: '/orders',
      query: { status },
    });
  }

  async getOrder(id: string) {
    const order = await this.ordersRepo.findOne({ where: { id } });
    if (!order) throw new NotFoundException(`Lab order ${id} not found`);
    const qr = order.qrCodeId
      ? await this.qrRepo.findOne({ where: { id: order.qrCodeId } })
      : null;

    // Per-test QR labels (generated by clinical-service). Join with the panel.
    const qrs = await this.qrRepo.find({ where: { serviceRequestId: id } });
    const byKey = new Map(
      qrs
        .filter((q) => q.testCode)
        .map((q) => [`${q.testCode}:${q.testIndex}`, q]),
    );
    const tests = (order.testPanel ?? []).map((t, i) => ({
      testCode: t.code,
      display: t.display,
      qrBase64: byKey.get(`${t.code}:${i}`)?.imageBase64 ?? null,
    }));

    return {
      ...toFhirServiceRequest(order),
      qrCode: qr ? { id: qr.id, imageBase64: qr.imageBase64 } : null,
      tests,
    };
  }

  async scanQr(dto: ScanQrDto, performerId: string) {
    const { orderId, testCode, testIndex } = parseLabQr(dto.qrData);

    // Mark the specific per-test QR (or order-level QR) as scanned.
    let qr: QrCode | null;
    if (testCode != null) {
      qr = await this.qrRepo.findOne({
        where: { serviceRequestId: orderId, testCode },
      });
    } else {
      const all = await this.qrRepo.find({
        where: { serviceRequestId: orderId },
      });
      qr = all.find((q) => !q.testCode) ?? all[0] ?? null;
    }
    if (qr && !qr.scannedAt) {
      qr.scannedAt = new Date();
      qr.scannedBy = performerId;
      await this.qrRepo.save(qr);
    }

    // Mark order as received
    const order = await this.ordersRepo.findOne({ where: { id: orderId } });
    if (!order) throw new NotFoundException(`Lab order not found for QR data`);
    if (!order.receivedAt) {
      order.receivedAt = new Date();
      order.performerId = performerId;
      await this.ordersRepo.save(order);
    }

    const scannedTest =
      testCode != null
        ? {
            testCode,
            testIndex,
            display:
              (order.testPanel ?? []).find((t) => t.code === testCode)
                ?.display ?? testCode,
          }
        : null;
    return { ...toFhirServiceRequest(order), scannedTest };
  }

  async receiveOrder(id: string, performerId: string) {
    const order = await this.ordersRepo.findOne({ where: { id } });
    if (!order) throw new NotFoundException(`Lab order ${id} not found`);
    order.receivedAt = new Date();
    order.performerId = performerId;
    const saved = await this.ordersRepo.save(order);
    return toFhirServiceRequest(saved);
  }

  /**
   * Records an order's results, with their PDF report, and completes the order
   * in one transaction, so they are saved whole or not at all. The order is
   * claimed first: results for an order that is no longer active (already
   * reported, or revoked) get a 409, so a double submit can't file two reports.
   * The ordering practitioner is notified in the same transaction.
   */
  async enterResults(dto: EnterResultsDto, performer: AuthUser) {
    const order = await this.ordersRepo.findOne({
      where: { id: dto.serviceRequestId },
    });
    if (!order)
      throw new NotFoundException(
        `Lab order ${dto.serviceRequestId} not found`,
      );
    const performerId = actorId(performer);
    const now = new Date();
    // Compared as text: an order's patientId is not validated as a uuid.
    const patient = await this.patientsRepo
      .createQueryBuilder('p')
      .select(['p.firstName', 'p.lastName', 'p.patientCode'])
      .where('p.id::text = :id', { id: order.patientId })
      .getOne();
    const patientName = patient
      ? `${patient.firstName} ${patient.lastName} (${patient.patientCode})`
      : `patient ${order.patientId}`;

    // Rendered before the transaction opens, so no rows stay locked meanwhile.
    const pdfBase64 = await generateLabReportPdf({
      patientName: `Patient ${order.patientId}`,
      patientCode: order.patientId,
      birthDate: 'On file',
      testName: order.display,
      results: dto.results,
      conclusion: dto.conclusion,
      labStaffName: performer.name ?? performer.email,
      clinicName: 'Curo Medical Center',
      reportDate: now.toLocaleDateString(),
    });

    const report = await this.dataSource.transaction(async (em) => {
      const { affected } = await em.update(
        ServiceRequest,
        { id: order.id, status: ServiceRequestStatus.ACTIVE },
        { status: ServiceRequestStatus.COMPLETED, completedAt: now },
      );
      if (!affected)
        throw new ConflictException(`Lab order ${order.id} is not active`);

      await em.save(
        Observation,
        dto.results.map((r) => ({
          patientId: order.patientId,
          practitionerId: performerId,
          serviceRequestId: order.id,
          status: ObservationStatus.FINAL,
          category: 'laboratory',
          code: r.code,
          display: r.display,
          valueQuantity: r.value,
          valueUnit: r.unit,
          valueString: r.valueString,
          interpretation: r.interpretation,
          referenceRangeLow: r.referenceRangeLow,
          referenceRangeHigh: r.referenceRangeHigh,
          referenceRangeText: r.referenceRangeText,
          effectiveDateTime: now,
        })),
      );
      const report = await em.save(DiagnosticReport, {
        patientId: order.patientId,
        serviceRequestId: order.id,
        performerId,
        status: DiagnosticReportStatus.FINAL,
        code: order.code,
        display: order.display,
        results: dto.results,
        conclusion: dto.conclusion,
        pdfBase64,
        effectiveDateTime: now,
        issued: now,
      });

      await notifyPractitioner(em, order.requesterId, {
        eventType: NotificationEventType.LAB_RESULTS_READY,
        title: 'Lab results ready',
        message: `${order.display} results for ${patientName} are ready to review.`,
        relatedResourceType: 'DiagnosticReport',
        relatedResourceId: report.id,
      });
      return report;
    });

    return toFhirReport(report);
  }

  async getReports(patientId?: string, pagination: PaginationQuery = {}) {
    const { page, pageSize, skip, take } = parsePagination(pagination);
    const where = patientId ? { patientId } : {};
    const [reports, total] = await this.reportsRepo.findAndCount({
      where,
      order: { issued: 'DESC' },
      skip,
      take,
    });
    return toSearchset(reports.map(toFhirReport), total, {
      page,
      pageSize,
      baseUrl: '/reports',
      query: { patientId },
    });
  }

  async getReport(id: string) {
    const r = await this.reportsRepo.findOne({ where: { id } });
    if (!r) throw new NotFoundException(`Report ${id} not found`);
    return toFhirReport(r);
  }

  // Instruments
  async getInstruments(): Promise<LabInstrument[]> {
    return this.instrumentsRepo.find();
  }

  async getQcLogs(
    filters?: { instrumentId?: string; status?: QCStatus },
    pagination: PaginationQuery = {},
  ) {
    const { page, pageSize, skip, take } = parsePagination(pagination);
    const where: FindOptionsWhere<QCLog> = {
      ...(filters?.instrumentId && { instrumentId: filters.instrumentId }),
      ...(filters?.status && { status: filters.status }),
    };
    const [logs, total] = await this.qcLogRepo.findAndCount({
      where,
      order: { performedAt: 'DESC' },
      skip,
      take,
    });
    return toSearchset(logs, total, {
      page,
      pageSize,
      baseUrl: '/qc-logs',
      query: { ...filters },
    });
  }

  async getLabStaff() {
    // practitioners is owned by the auth service, so it is read with raw SQL.
    const rows = await this.dataSource.query<LabStaffRow[]>(`
      SELECT id, "firstName", "lastName", email, specialization, qualification, active
      FROM practitioners
      WHERE role = 'LAB_STAFF'
      ORDER BY "firstName", "lastName"
    `);

    return rows.map((row) => ({
      id: row.id,
      name: {
        first: row.firstName,
        last: row.lastName,
        full: `${row.firstName} ${row.lastName}`,
      },
      role: 'technician',
      department: row.specialization ?? 'Laboratory',
      employeeId: row.id,
      email: row.email,
      phone: '',
      qualifications: row.qualification ? [row.qualification] : [],
      activeShift: 'morning',
      joinedAt: '',
      active: row.active,
    }));
  }

  async updateInstrumentStatus(
    id: string,
    status: InstrumentStatus,
    notes?: string,
  ): Promise<LabInstrument> {
    const instrument = await this.instrumentsRepo.findOne({ where: { id } });
    if (!instrument) throw new NotFoundException(`Instrument ${id} not found`);
    instrument.status = status;
    if (notes) instrument.notes = notes;
    if (status === InstrumentStatus.MAINTENANCE)
      instrument.lastMaintenanceDate = new Date().toISOString().split('T')[0];
    return this.instrumentsRepo.save(instrument);
  }

  async createInstrument(dto: CreateInstrumentDto): Promise<LabInstrument> {
    const instrument = this.instrumentsRepo.create(dto);
    return this.instrumentsRepo.save(instrument);
  }

  // TAT calculation
  async getTatStats() {
    const completed = await this.ordersRepo.find({
      where: { status: ServiceRequestStatus.COMPLETED },
    });
    const withTat = completed.filter((o) => o.receivedAt && o.completedAt);
    if (!withTat.length) return { averageTatMinutes: null, count: 0 };

    const tats = withTat.map(
      (o) => (o.completedAt.getTime() - o.receivedAt.getTime()) / 60000,
    );
    const avg = tats.reduce((a, b) => a + b, 0) / tats.length;
    return { averageTatMinutes: Math.round(avg), count: withTat.length, tats };
  }
}
