import { Injectable, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { DataSource, Repository } from 'typeorm';
import { ServiceRequest, Observation, QrCode } from '@curo/shared/database';
import { ServiceRequestStatus, ObservationStatus } from '@curo/shared/enums';
import {
  parsePagination,
  toSearchset,
  PaginationQuery,
} from '@curo/shared/fhir';
import { DiagnosticReport } from '../entities/diagnostic-report.entity';
import { LabInstrument } from '../entities/lab-instrument.entity';
import { LabTestCatalog } from '../entities/lab-test-catalog.entity';
import { QCLog, QCStatus } from '../entities/qc-log.entity';
import { EnterResultsDto } from './dto/enter-results.dto';
import { ScanQrDto } from './dto/scan-qr.dto';
import { DiagnosticReportStatus, InstrumentStatus } from '../enums';
import { generateLabReportPdf } from './pdf.generator';

function toFhirServiceRequest(s: ServiceRequest) {
  return {
    resourceType: 'ServiceRequest',
    id: s.id,
    status: s.status,
    code: { coding: [{ code: s.code, display: s.display }] },
    subject: { reference: `Patient/${s.patientId}` },
    requester: { reference: `Practitioner/${s.requesterId}` },
    authoredOn: s.authoredOn,
    priority: s.priority,
    testPanel: s.testPanel,
    receivedAt: s.receivedAt,
    completedAt: s.completedAt,
  };
}

function toFhirReport(r: DiagnosticReport) {
  return {
    resourceType: 'DiagnosticReport',
    id: r.id,
    status: r.status,
    code: { coding: [{ code: r.code, display: r.display }] },
    subject: { reference: `Patient/${r.patientId}` },
    performer: [{ reference: `Practitioner/${r.performerId}` }],
    basedOn: [{ reference: `ServiceRequest/${r.serviceRequestId}` }],
    effectiveDateTime: r.effectiveDateTime,
    issued: r.issued,
    conclusion: r.conclusion,
    result: (r.results || []).map((res: any) => ({ display: res.display })),
    presentedForm: r.pdfBase64
      ? [{ contentType: 'application/pdf', data: r.pdfBase64 }]
      : [],
  };
}

@Injectable()
export class LabService {
  constructor(
    @InjectRepository(ServiceRequest)
    private ordersRepo: Repository<ServiceRequest>,
    @InjectRepository(DiagnosticReport)
    private reportsRepo: Repository<DiagnosticReport>,
    @InjectRepository(Observation)
    private observationsRepo: Repository<Observation>,
    @InjectRepository(QrCode)
    private qrRepo: Repository<QrCode>,
    @InjectRepository(LabInstrument)
    private instrumentsRepo: Repository<LabInstrument>,
    @InjectRepository(LabTestCatalog)
    private catalogRepo: Repository<LabTestCatalog>,
    @InjectRepository(QCLog)
    private qcLogRepo: Repository<QCLog>,
    private dataSource: DataSource,
  ) {}

  // Tests a given lab offers (doctors browse before ordering).
  async getCatalog(organizationId?: string): Promise<LabTestCatalog[]> {
    const where: any = { active: true };
    if (organizationId) where.organizationId = organizationId;
    return this.catalogRepo.find({ where, order: { name: 'ASC' } });
  }

  // Lab orders queue → FHIR searchset Bundle (paginated, optional status filter).
  async getOrders(
    status?: string,
    pagination: PaginationQuery = {},
  ): Promise<any> {
    const { page, pageSize, skip, take } = parsePagination(pagination);
    const query = this.ordersRepo.createQueryBuilder('s');
    if (status) query.where('s.status = :status', { status });
    const [orders, total] = await query
      .orderBy('s.authoredOn', 'ASC')
      .skip(skip)
      .take(take)
      .getManyAndCount();
    return toSearchset(orders.map(toFhirServiceRequest), total, {
      page,
      pageSize,
      baseUrl: '/orders',
      query: { status },
    });
  }

  async getOrder(id: string): Promise<any> {
    const order = await this.ordersRepo.findOne({ where: { id } });
    if (!order) throw new NotFoundException(`Lab order ${id} not found`);
    const qr = order.qrCodeId
      ? await this.qrRepo.findOne({ where: { id: order.qrCodeId } })
      : null;

    // Per-test QR labels (generated by clinical-service). Join with the panel.
    const qrs = await this.qrRepo.find({ where: { serviceRequestId: id } });
    const byKey = new Map(
      qrs
        .filter((q) => q.testCode)
        .map((q) => [`${q.testCode}:${q.testIndex}`, q]),
    );
    const tests = (order.testPanel ?? []).map((t: any, i: number) => ({
      testCode: t.code,
      display: t.display,
      qrBase64: byKey.get(`${t.code}:${i}`)?.imageBase64 ?? null,
    }));

    return {
      ...toFhirServiceRequest(order),
      qrCode: qr ? { id: qr.id, imageBase64: qr.imageBase64 } : null,
      tests,
    };
  }

  async scanQr(dto: ScanQrDto, performerId: string): Promise<any> {
    // QR encodes either an order-level URL (.../lab/orders/:id) or a per-test URL
    // (.../lab/orders/:id?test=<code>&i=<index>). Resolve order id + optional test.
    const { orderId, testCode, testIndex } = this.parseQrData(dto.qrData);

    // Mark the specific per-test QR (or order-level QR) as scanned.
    let qr: QrCode | null;
    if (testCode != null) {
      qr = await this.qrRepo.findOne({
        where: { serviceRequestId: orderId, testCode },
      });
    } else {
      const all = await this.qrRepo.find({
        where: { serviceRequestId: orderId },
      });
      qr = all.find((q) => !q.testCode) ?? all[0] ?? null;
    }
    if (qr && !qr.scannedAt) {
      qr.scannedAt = new Date();
      qr.scannedBy = performerId;
      await this.qrRepo.save(qr);
    }

    // Mark order as received
    const order = await this.ordersRepo.findOne({ where: { id: orderId } });
    if (!order) throw new NotFoundException(`Lab order not found for QR data`);
    if (!order.receivedAt) {
      order.receivedAt = new Date();
      order.performerId = performerId;
      await this.ordersRepo.save(order);
    }

    const scannedTest =
      testCode != null
        ? {
            testCode,
            testIndex,
            display:
              (order.testPanel ?? []).find((t: any) => t.code === testCode)
                ?.display ?? testCode,
          }
        : null;
    return { ...toFhirServiceRequest(order), scannedTest };
  }

  private parseQrData(raw: string): {
    orderId: string;
    testCode?: string;
    testIndex?: number;
  } {
    const [path, qs] = raw.split('?');
    const segs = path.split('/').filter(Boolean);
    const ordersIdx = segs.indexOf('orders');
    const orderId =
      ordersIdx >= 0 && segs[ordersIdx + 1]
        ? segs[ordersIdx + 1]
        : segs[segs.length - 1];
    let testCode: string | undefined;
    let testIndex: number | undefined;
    if (qs) {
      const sp = new URLSearchParams(qs);
      testCode = sp.get('test') ?? undefined;
      const i = sp.get('i');
      testIndex = i != null ? parseInt(i, 10) : undefined;
    }
    return { orderId, testCode, testIndex };
  }

  async receiveOrder(id: string, performerId: string): Promise<any> {
    const order = await this.ordersRepo.findOne({ where: { id } });
    if (!order) throw new NotFoundException(`Lab order ${id} not found`);
    order.receivedAt = new Date();
    order.performerId = performerId;
    const saved = await this.ordersRepo.save(order);
    return toFhirServiceRequest(saved);
  }

  // Enter results and generate PDF report
  async enterResults(dto: EnterResultsDto, performerId: string): Promise<any> {
    const order = await this.ordersRepo.findOne({
      where: { id: dto.serviceRequestId },
    });
    if (!order)
      throw new NotFoundException(
        `Lab order ${dto.serviceRequestId} not found`,
      );

    // Save individual observations
    for (const r of dto.results) {
      const obs = this.observationsRepo.create({
        patientId: order.patientId,
        practitionerId: performerId,
        serviceRequestId: order.id,
        status: ObservationStatus.FINAL,
        category: 'laboratory',
        code: r.code,
        display: r.display,
        valueQuantity: r.value,
        valueUnit: r.unit,
        valueString: r.valueString,
        interpretation: r.interpretation,
        referenceRangeLow: r.referenceRangeLow,
        referenceRangeHigh: r.referenceRangeHigh,
        referenceRangeText: r.referenceRangeText,
        effectiveDateTime: new Date(),
      });
      await this.observationsRepo.save(obs);
    }

    // Generate PDF report
    const pdfBase64 = await generateLabReportPdf({
      patientName: `Patient ${order.patientId}`,
      patientCode: order.patientId,
      birthDate: 'On file',
      testName: order.display,
      results: dto.results,
      conclusion: dto.conclusion,
      labStaffName: `Staff ${performerId}`,
      clinicName: 'Curo Medical Center',
      reportDate: new Date().toLocaleDateString(),
    });

    // Create DiagnosticReport
    const reportData: Partial<DiagnosticReport> = {
      patientId: order.patientId,
      serviceRequestId: order.id,
      performerId,
      status: DiagnosticReportStatus.FINAL,
      code: order.code,
      display: order.display,
      results: dto.results as unknown as Record<string, unknown>[],
      conclusion: dto.conclusion,
      pdfBase64,
      effectiveDateTime: new Date(),
      issued: new Date(),
    };
    const savedReports = await this.reportsRepo.save([
      reportData as DiagnosticReport,
    ]);
    const savedReport = savedReports[0];

    // Mark order as completed
    await this.ordersRepo.update(order.id, {
      status: ServiceRequestStatus.COMPLETED,
      completedAt: new Date(),
    });

    return toFhirReport(savedReport);
  }

  async getReports(
    patientId?: string,
    pagination: PaginationQuery = {},
  ): Promise<any> {
    const { page, pageSize, skip, take } = parsePagination(pagination);
    const where = patientId ? { patientId } : {};
    const [reports, total] = await this.reportsRepo.findAndCount({
      where,
      order: { issued: 'DESC' },
      skip,
      take,
    });
    return toSearchset(reports.map(toFhirReport), total, {
      page,
      pageSize,
      baseUrl: '/reports',
      query: { patientId },
    });
  }

  async getReport(id: string): Promise<any> {
    const r = await this.reportsRepo.findOne({ where: { id } });
    if (!r) throw new NotFoundException(`Report ${id} not found`);
    return toFhirReport(r);
  }

  // Instruments
  async getInstruments(): Promise<LabInstrument[]> {
    return this.instrumentsRepo.find();
  }

  async getQcLogs(
    filters?: { instrumentId?: string; status?: QCStatus },
    pagination: PaginationQuery = {},
  ): Promise<any> {
    const { page, pageSize, skip, take } = parsePagination(pagination);
    const where: any = {};
    if (filters?.instrumentId) where.instrumentId = filters.instrumentId;
    if (filters?.status) where.status = filters.status;
    const [logs, total] = await this.qcLogRepo.findAndCount({
      where,
      order: { performedAt: 'DESC' },
      skip,
      take,
    });
    return toSearchset(logs, total, {
      page,
      pageSize,
      baseUrl: '/qc-logs',
      query: { ...filters },
    });
  }

  async getLabStaff(): Promise<any[]> {
    const rows = await this.dataSource.query(`
      SELECT id, "firstName", "lastName", email, specialization, qualification, active
      FROM practitioners
      WHERE role = 'LAB_STAFF'
      ORDER BY "firstName", "lastName"
    `);

    return rows.map((row: any) => ({
      id: row.id,
      name: {
        first: row.firstName,
        last: row.lastName,
        full: `${row.firstName} ${row.lastName}`,
      },
      role: 'technician',
      department: row.specialization ?? 'Laboratory',
      employeeId: row.id,
      email: row.email,
      phone: '',
      qualifications: row.qualification ? [row.qualification] : [],
      activeShift: 'morning',
      joinedAt: '',
      active: row.active,
    }));
  }

  async updateInstrumentStatus(
    id: string,
    status: InstrumentStatus,
    notes?: string,
  ): Promise<LabInstrument> {
    const instrument = await this.instrumentsRepo.findOne({ where: { id } });
    if (!instrument) throw new NotFoundException(`Instrument ${id} not found`);
    instrument.status = status;
    if (notes) instrument.notes = notes;
    if (status === InstrumentStatus.MAINTENANCE)
      instrument.lastMaintenanceDate = new Date().toISOString().split('T')[0];
    return this.instrumentsRepo.save(instrument);
  }

  async createInstrument(dto: Partial<LabInstrument>): Promise<LabInstrument> {
    const instrument = this.instrumentsRepo.create(dto);
    return this.instrumentsRepo.save(instrument);
  }

  // TAT calculation
  async getTatStats(): Promise<any> {
    const completed = await this.ordersRepo.find({
      where: { status: ServiceRequestStatus.COMPLETED },
    });
    const withTat = completed.filter((o) => o.receivedAt && o.completedAt);
    if (!withTat.length) return { averageTatMinutes: null, count: 0 };

    const tats = withTat.map(
      (o) => (o.completedAt.getTime() - o.receivedAt.getTime()) / 60000,
    );
    const avg = tats.reduce((a, b) => a + b, 0) / tats.length;
    return { averageTatMinutes: Math.round(avg), count: withTat.length, tats };
  }
}
