import { MigrationInterface, QueryRunner } from "typeorm";

/**
 * The schema as TypeORM `synchronize` left it on 2026-10-06, when services
 * stopped managing the schema themselves. Generated from the entities against
 * an empty database; `npm run db:check` against a synchronize-built database
 * reported no differences.
 */
export class Baseline1791271595506 implements MigrationInterface {
    name = 'Baseline1791271595506'

    public async up(queryRunner: QueryRunner): Promise<void> {
        // Baseline-on-migrate: databases created before migrations existed already
        // have this schema. Record the baseline as applied and leave them untouched.
        if (await queryRunner.hasTable('users')) return;

        // Previously created by scripts/init.sql when the Postgres volume was first initialised.
        await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS "uuid-ossp"`);
        await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS "pgcrypto"`);
        await queryRunner.query(`CREATE TYPE "public"."appointments_status_enum" AS ENUM('proposed', 'pending', 'booked', 'arrived', 'fulfilled', 'cancelled', 'noshow', 'waitlist')`);
        await queryRunner.query(`CREATE TABLE "appointments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "patientId" character varying NOT NULL, "practitionerId" character varying NOT NULL, "status" "public"."appointments_status_enum" NOT NULL DEFAULT 'booked', "start" TIMESTAMP NOT NULL, "end" TIMESTAMP NOT NULL, "description" character varying, "serviceType" character varying, "reasonCode" character varying, "comment" character varying, "slotNumber" integer, "encounterId" character varying, "isWalkIn" boolean NOT NULL DEFAULT false, "cancelledReason" character varying, "queueStage" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4a437a9a27e948726b8bb3e36ad" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_13c2e57cb81b44f062ba24df57" ON "appointments"  ("patientId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ad15a26d54ed5b5b383c628e61" ON "appointments"  ("practitionerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_3b5db6bf48bf93dea5e162a7e7" ON "appointments"  ("queueStage") `);
        await queryRunner.query(`CREATE TABLE "payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "patientId" character varying NOT NULL, "appointmentId" character varying, "encounterId" character varying, "serviceRequestId" character varying, "medicationDispenseId" character varying, "collectedBy" character varying, "type" character varying, "amount" numeric(10,2) NOT NULL, "currency" character varying, "paymentMethod" character varying, "status" character varying, "receiptNumber" character varying, "notes" character varying, "paidAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e1f738d342393a3c19867610f2" ON "payments"  ("patientId") `);
        await queryRunner.query(`CREATE INDEX "IDX_90213a20c94916e46cd2131364" ON "payments"  ("appointmentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_08ebbe1dbd48e11deb2c73a9ea" ON "payments"  ("collectedBy") `);
        await queryRunner.query(`CREATE TABLE "organizations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "type" character varying, "phone" character varying, "email" character varying, "addressLine1" character varying, "city" character varying, "licenseNumber" character varying, "active" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6b031fcd0863e3f6b44230163f9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."practitioners_gender_enum" AS ENUM('male', 'female', 'other', 'unknown')`);
        await queryRunner.query(`CREATE TYPE "public"."practitioners_role_enum" AS ENUM('PATIENT', 'DOCTOR', 'RECEPTIONIST', 'PHARMACIST', 'LAB_STAFF', 'NURSE', 'SUPER_ADMIN')`);
        await queryRunner.query(`CREATE TABLE "practitioners" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "firstName" character varying NOT NULL, "lastName" character varying NOT NULL, "middleName" character varying, "gender" "public"."practitioners_gender_enum" NOT NULL DEFAULT 'unknown', "phone" character varying, "email" character varying, "specialization" character varying, "qualification" character varying, "licenseNumber" character varying, "role" "public"."practitioners_role_enum" NOT NULL, "organizationId" character varying, "photo" character varying, "active" boolean NOT NULL DEFAULT true, "userId" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_88941574a3e4fe907d36ee2f8cc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "clinical_notes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "encounterId" character varying NOT NULL, "patientId" character varying NOT NULL, "practitionerId" character varying NOT NULL, "subjective" text, "objective" text, "assessment" text, "plan" text, "additionalNotes" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_590ad4cecf429ecc12e8202cbb4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3726ec59405ae597e8cb96f9de" ON "clinical_notes"  ("encounterId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f3aad3f611d98765f4c30adba9" ON "clinical_notes"  ("patientId") `);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('PATIENT', 'DOCTOR', 'RECEPTIONIST', 'PHARMACIST', 'LAB_STAFF', 'NURSE', 'SUPER_ADMIN')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying NOT NULL, "passwordHash" character varying NOT NULL, "role" "public"."users_role_enum" NOT NULL, "patientId" character varying, "practitionerId" character varying, "isActive" boolean NOT NULL DEFAULT true, "refreshToken" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users"  ("email") `);
        await queryRunner.query(`CREATE TYPE "public"."encounters_status_enum" AS ENUM('planned', 'in-progress', 'onhold', 'discharged', 'completed', 'cancelled', 'entered-in-error')`);
        await queryRunner.query(`CREATE TABLE "encounters" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "patientId" character varying NOT NULL, "practitionerId" character varying NOT NULL, "appointmentId" character varying, "status" "public"."encounters_status_enum" NOT NULL DEFAULT 'in-progress', "classCode" character varying, "serviceType" character varying, "priority" character varying, "periodStart" TIMESTAMP WITH TIME ZONE, "periodEnd" TIMESTAMP WITH TIME ZONE, "reasonCode" character varying, "dischargeDisposition" character varying, "fhirExtensions" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b2e596be58aabc4ccc8f8458b53" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_79528cb799cc63dadd8895fd9b" ON "encounters"  ("patientId") `);
        await queryRunner.query(`CREATE INDEX "IDX_62a05cf983cb708f61c552aa0e" ON "encounters"  ("practitionerId") `);
        await queryRunner.query(`CREATE TABLE "icd10_codes" ("code" character varying NOT NULL, "name" character varying NOT NULL, "keywords" jsonb, CONSTRAINT "PK_f455ed8ffc710ef8cf5513bf82a" PRIMARY KEY ("code"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d689209e0449acea80b52a0dd6" ON "icd10_codes"  ("name") `);
        await queryRunner.query(`CREATE TYPE "public"."tasks_status_enum" AS ENUM('draft', 'requested', 'received', 'accepted', 'in-progress', 'completed', 'cancelled', 'failed')`);
        await queryRunner.query(`CREATE TABLE "tasks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "ownerId" character varying NOT NULL, "patientId" character varying, "encounterId" character varying, "status" "public"."tasks_status_enum" NOT NULL DEFAULT 'requested', "description" character varying NOT NULL, "priority" character varying, "code" character varying, "focus" character varying, "note" character varying, "authoredOn" TIMESTAMP WITH TIME ZONE, "lastModified" TIMESTAMP WITH TIME ZONE, "restriction" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8d12ff38fcc62aaba2cab748772" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_607de52438268ab19a40634942" ON "tasks"  ("ownerId") `);
        await queryRunner.query(`CREATE TYPE "public"."diagnostic_reports_status_enum" AS ENUM('registered', 'partial', 'preliminary', 'final', 'amended', 'corrected', 'appended', 'cancelled', 'entered-in-error', 'unknown')`);
        await queryRunner.query(`CREATE TABLE "diagnostic_reports" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "patientId" character varying NOT NULL, "serviceRequestId" character varying NOT NULL, "performerId" character varying NOT NULL, "status" "public"."diagnostic_reports_status_enum" NOT NULL DEFAULT 'registered', "code" character varying NOT NULL, "display" character varying NOT NULL, "results" jsonb, "conclusion" character varying, "pdfBase64" character varying, "pdfPath" character varying, "effectiveDateTime" TIMESTAMP WITH TIME ZONE, "issued" TIMESTAMP WITH TIME ZONE, "presentedForm" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_cde1159541fdedf6e20fa48e6ec" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_fe9c62349352fdaae7f60d0cf9" ON "diagnostic_reports"  ("patientId") `);
        await queryRunner.query(`CREATE INDEX "IDX_5aea591bf732989a6b227e06a7" ON "diagnostic_reports"  ("serviceRequestId") `);
        await queryRunner.query(`CREATE TYPE "public"."lab_qc_logs_status_enum" AS ENUM('pass', 'fail', 'warning')`);
        await queryRunner.query(`CREATE TABLE "lab_qc_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "instrumentId" character varying NOT NULL, "testCode" character varying NOT NULL, "controlLevel" character varying NOT NULL, "expectedValue" numeric(12,4) NOT NULL, "observedValue" numeric(12,4) NOT NULL, "unit" character varying, "status" "public"."lab_qc_logs_status_enum" NOT NULL DEFAULT 'pass', "performedBy" character varying NOT NULL, "performedAt" TIMESTAMP WITH TIME ZONE NOT NULL, "notes" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_477394a2c75de94c8a8ca15fae9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_83998383efaed63bd404ed1291" ON "lab_qc_logs"  ("instrumentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_5997078557c2a18182d87f881e" ON "lab_qc_logs"  ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_43bb9e5006891e2f3976189c53" ON "lab_qc_logs"  ("performedAt") `);
        await queryRunner.query(`CREATE TYPE "public"."lab_instruments_status_enum" AS ENUM('operational', 'maintenance', 'offline')`);
        await queryRunner.query(`CREATE TABLE "lab_instruments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "model" character varying, "manufacturer" character varying, "serialNumber" character varying, "status" "public"."lab_instruments_status_enum" NOT NULL DEFAULT 'operational', "location" character varying, "category" character varying, "lastMaintenanceDate" date, "nextMaintenanceDate" date, "notes" character varying, "responsibleTechnicianId" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a3da1b9f8555b04ae6b9e28e01a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "lab_test_catalog" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organizationId" character varying, "code" character varying NOT NULL, "name" character varying NOT NULL, "category" character varying, "specimen" character varying, "price" numeric(10,2), "active" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_07b402b98cf8a046916370c1032" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_dabc8c776643923502955690d2" ON "lab_test_catalog"  ("organizationId") `);
        await queryRunner.query(`CREATE TYPE "public"."notifications_eventtype_enum" AS ENUM('appointment_confirmed', 'appointment_cancelled', 'prescription_ready', 'lab_results_ready', 'low_stock_alert', 'general')`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "recipientId" character varying NOT NULL, "recipientRole" character varying, "eventType" "public"."notifications_eventtype_enum" NOT NULL DEFAULT 'general', "title" character varying NOT NULL, "message" text NOT NULL, "relatedResourceId" character varying, "relatedResourceType" character varying, "isRead" boolean NOT NULL DEFAULT false, "readAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_db873ba9a123711a4bff527ccd" ON "notifications"  ("recipientId") `);
        await queryRunner.query(`CREATE TYPE "public"."allergy_intolerances_type_enum" AS ENUM('allergy', 'intolerance')`);
        await queryRunner.query(`CREATE TYPE "public"."allergy_intolerances_criticality_enum" AS ENUM('low', 'high', 'unable-to-assess')`);
        await queryRunner.query(`CREATE TABLE "allergy_intolerances" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "patientId" character varying NOT NULL, "practitionerId" character varying NOT NULL, "type" "public"."allergy_intolerances_type_enum" NOT NULL DEFAULT 'allergy', "criticality" "public"."allergy_intolerances_criticality_enum" NOT NULL DEFAULT 'low', "code" character varying NOT NULL, "display" character varying NOT NULL, "category" character varying, "clinicalStatus" character varying, "verificationStatus" character varying, "reactions" jsonb, "onsetDate" date, "note" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2ddbbefc358e20a95a1a10af013" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_13ddd8e3259ed3c655b609dd4b" ON "allergy_intolerances"  ("patientId") `);
        await queryRunner.query(`CREATE TYPE "public"."conditions_clinicalstatus_enum" AS ENUM('active', 'recurrence', 'relapse', 'inactive', 'remission', 'resolved')`);
        await queryRunner.query(`CREATE TABLE "conditions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "patientId" character varying NOT NULL, "encounterId" character varying, "practitionerId" character varying NOT NULL, "clinicalStatus" "public"."conditions_clinicalstatus_enum" NOT NULL DEFAULT 'active', "verificationStatus" character varying, "category" character varying, "severity" character varying, "code" character varying NOT NULL, "display" character varying NOT NULL, "bodySite" character varying, "onsetDate" date, "abatementDate" date, "note" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3938bdf2933c08ac7af7e0e15e7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_dda209e2eefed614fa0ac604c6" ON "conditions"  ("patientId") `);
        await queryRunner.query(`CREATE TABLE "document_references" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "patientId" character varying NOT NULL, "authorId" character varying NOT NULL, "encounterId" character varying, "relatedResourceId" character varying, "relatedResourceType" character varying, "status" character varying, "docStatus" character varying, "type" character varying NOT NULL, "description" character varying, "contentType" character varying, "fileBase64" character varying, "filePath" character varying, "fileSize" integer, "fileName" character varying, "date" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9e61eb7b11a30ba2d7eaa2508f7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0b1e4e49c4f7fb429b4097daa5" ON "document_references"  ("patientId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b8a081f8ecc40bfe9ac76c3608" ON "document_references"  ("encounterId") `);
        await queryRunner.query(`CREATE TABLE "medication_catalog" ("id" character varying NOT NULL, "name" character varying NOT NULL, "genericName" character varying, "form" character varying, "strength" character varying, "atc" character varying, "commonSubstitutes" jsonb, "active" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3b2f106a86ab5faeab3f780667e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7cee508a6a8983eb9240717375" ON "medication_catalog"  ("name") `);
        await queryRunner.query(`CREATE TYPE "public"."medication_dispenses_status_enum" AS ENUM('preparation', 'in-progress', 'cancelled', 'on-hold', 'completed', 'entered-in-error', 'stopped', 'declined', 'unknown')`);
        await queryRunner.query(`CREATE TABLE "medication_dispenses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "medicationRequestId" character varying NOT NULL, "patientId" character varying NOT NULL, "pharmacistId" character varying NOT NULL, "status" "public"."medication_dispenses_status_enum" NOT NULL DEFAULT 'in-progress', "medicationCode" character varying NOT NULL, "medicationDisplay" character varying NOT NULL, "quantityValue" integer, "quantityUnit" character varying, "daysSupply" integer, "dosageText" character varying, "dispenserName" character varying, "unitPrice" numeric(10,2), "totalPrice" numeric(10,2), "receiptNumber" character varying, "batchNumber" character varying, "note" character varying, "whenHandedOver" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_01892203a6f438a6073f110a921" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8d574a203534247577d558de6f" ON "medication_dispenses"  ("medicationRequestId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d2cf80f79ef3bfce5cbe8c7596" ON "medication_dispenses"  ("patientId") `);
        await queryRunner.query(`CREATE TABLE "stock" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "medicationCode" character varying NOT NULL, "medicationName" character varying NOT NULL, "genericName" character varying, "form" character varying, "strength" character varying, "quantity" integer NOT NULL DEFAULT '0', "unit" character varying, "expiryDate" date, "reorderThreshold" integer NOT NULL DEFAULT '10', "unitPrice" numeric(10,2), "supplier" character varying, "batchNumber" character varying, "storageLocation" character varying, "organizationId" character varying, "active" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_092bc1fc7d860426a1dec5aa8e9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" character varying NOT NULL, "userRole" character varying, "action" character varying NOT NULL, "resourceType" character varying NOT NULL, "resourceId" character varying NOT NULL, "patientId" character varying, "ipAddress" character varying, "userAgent" character varying, "changes" jsonb, "outcome" character varying, "outcomeDescription" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cfa83f61e4d27a87fcae1e025a" ON "audit_logs"  ("userId") `);
        await queryRunner.query(`CREATE TYPE "public"."medication_requests_status_enum" AS ENUM('active', 'on-hold', 'cancelled', 'completed', 'entered-in-error', 'stopped', 'draft')`);
        await queryRunner.query(`CREATE TABLE "medication_requests" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "patientId" character varying NOT NULL, "practitionerId" character varying NOT NULL, "encounterId" character varying, "status" "public"."medication_requests_status_enum" NOT NULL DEFAULT 'active', "intent" character varying, "medicationCode" character varying NOT NULL, "medicationDisplay" character varying NOT NULL, "dosageText" character varying, "route" character varying, "frequency" character varying, "durationDays" integer, "quantityValue" integer, "quantityUnit" character varying, "refillsAllowed" integer, "substitutionAllowed" boolean, "reasonCode" character varying, "note" character varying, "authoredOn" TIMESTAMP WITH TIME ZONE, "dispensedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f02d7c22090b5a549044e3f23bf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_22ff06c07aee1540a978b37be9" ON "medication_requests"  ("patientId") `);
        await queryRunner.query(`CREATE TYPE "public"."observations_status_enum" AS ENUM('registered', 'preliminary', 'final', 'amended', 'corrected', 'cancelled', 'entered-in-error', 'unknown')`);
        await queryRunner.query(`CREATE TABLE "observations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "patientId" character varying NOT NULL, "practitionerId" character varying NOT NULL, "encounterId" character varying, "appointmentId" character varying, "performerRole" character varying, "serviceRequestId" character varying, "status" "public"."observations_status_enum" NOT NULL DEFAULT 'final', "category" character varying, "code" character varying NOT NULL, "display" character varying NOT NULL, "valueQuantity" numeric(10,2), "valueUnit" character varying, "valueString" character varying, "interpretation" character varying, "referenceRangeLow" character varying, "referenceRangeHigh" character varying, "referenceRangeText" character varying, "bodySite" character varying, "components" jsonb, "effectiveDateTime" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f9208d64f50a76030758087c0ef" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_85a579df451034cd5f184b2a3c" ON "observations"  ("patientId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d342e0231dc00eab1c86649d92" ON "observations"  ("appointmentId") `);
        await queryRunner.query(`CREATE TYPE "public"."patients_gender_enum" AS ENUM('male', 'female', 'other', 'unknown')`);
        await queryRunner.query(`CREATE TYPE "public"."patients_maritalstatus_enum" AS ENUM('S', 'M', 'D', 'W', 'L', 'UNK')`);
        await queryRunner.query(`CREATE TABLE "patients" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "patientCode" character varying NOT NULL, "personalHealthNumber" character varying, "firstName" character varying NOT NULL, "lastName" character varying NOT NULL, "middleName" character varying, "birthDate" date, "gender" "public"."patients_gender_enum" DEFAULT 'unknown', "nic" character varying, "passportNumber" character varying, "maritalStatus" "public"."patients_maritalstatus_enum", "phone" character varying, "email" character varying, "addressLine1" character varying, "addressLine2" character varying, "city" character varying, "state" character varying, "postalCode" character varying, "country" character varying, "bloodType" character varying, "emergencyContactName" character varying, "emergencyContactPhone" character varying, "emergencyContactRelationship" character varying, "insuranceProvider" character varying, "insurancePolicyNumber" character varying, "insuranceGroupNumber" character varying, "photo" character varying, "userId" character varying, "active" boolean NOT NULL DEFAULT true, "fhirExtensions" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a7f0b9fcbb3469d5ec0b0aceaa7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_fc3a16a6402299412fc9423738" ON "patients"  ("patientCode") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_21bf26c962bdfa52b6ccb5b2a5" ON "patients"  ("personalHealthNumber") `);
        await queryRunner.query(`CREATE TABLE "qr_codes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "serviceRequestId" character varying NOT NULL, "testCode" character varying, "testIndex" integer, "encodedUrl" character varying NOT NULL, "imageBase64" text NOT NULL, "scannedAt" TIMESTAMP, "scannedBy" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4b7aa338e150a878ce9e2c55c5c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9a04a01f307487047b251b2664" ON "qr_codes"  ("serviceRequestId") `);
        await queryRunner.query(`CREATE TYPE "public"."service_requests_status_enum" AS ENUM('draft', 'active', 'on-hold', 'revoked', 'completed', 'entered-in-error', 'unknown')`);
        await queryRunner.query(`CREATE TABLE "service_requests" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "patientId" character varying NOT NULL, "requesterId" character varying NOT NULL, "encounterId" character varying, "performerId" character varying, "status" "public"."service_requests_status_enum" NOT NULL DEFAULT 'active', "intent" character varying, "category" character varying, "code" character varying NOT NULL, "display" character varying NOT NULL, "testPanel" jsonb, "priority" character varying, "reasonCode" character varying, "note" character varying, "qrCodeId" character varying, "authoredOn" TIMESTAMP WITH TIME ZONE, "occurrenceDateTime" TIMESTAMP WITH TIME ZONE, "receivedAt" TIMESTAMP WITH TIME ZONE, "completedAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ee60bcd826b7e130bfbd97daf66" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_536d371cae3e7c0375a8b58425" ON "service_requests"  ("patientId") `);
    }

    public async down(): Promise<void> {
        // Reverting the baseline would drop every table, patient records included.
        throw new Error('The baseline migration cannot be reverted. To start over, recreate the database.');
    }
}
